---
ansible_network_os: dellemc.enterprise_sonic.sonic
ansible_user: admin
ansible_password: admin123
ansible_python_interpreter: /usr/bin/python3
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
path_for_txt_file: './output/spine1_cli_output.txt'
network_subset_to_gather_spines:
  - min
network_resources_to_gather_spines:
  - vlans
  - bgp_neighbors
  - system
  - interfaces
  - lldp_global
  - port_group
  - lag_interfaces
  - mclag
  - l3_interfaces
  - vrfs
  - ntp
network_subset_to_gather_leaves:
  - min
network_resources_to_gather_leaves:
  - vlans
  - bgp_neighbors
  - system
  - interfaces
  - lldp_global
  - port_group
  - lag_interfaces
  - mclag
  - l3_interfaces
  - vrfs
  - ntp
  - vxlans
  - vlan_mapping
local_username: ben